// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: streamhive.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_UNKNOWN  JobStatus = 0
	JobStatus_STARTED  JobStatus = 1
	JobStatus_FINISHED JobStatus = 2
	JobStatus_STOPPED  JobStatus = 3
	JobStatus_FAILED   JobStatus = 4
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "STARTED",
		2: "FINISHED",
		3: "STOPPED",
		4: "FAILED",
	}
	JobStatus_value = map[string]int32{
		"UNKNOWN":  0,
		"STARTED":  1,
		"FINISHED": 2,
		"STOPPED":  3,
		"FAILED":   4,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_streamhive_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_streamhive_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_streamhive_proto_rawDescGZIP(), []int{0}
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamUrl     string                 `protobuf:"bytes,1,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_streamhive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamhive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_streamhive_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_streamhive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamhive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_streamhive_proto_rawDescGZIP(), []int{1}
}

func (x *StartResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_streamhive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamhive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_streamhive_proto_rawDescGZIP(), []int{2}
}

func (x *StopRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        JobStatus              `protobuf:"varint,1,opt,name=status,proto3,enum=streamhive.JobStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_streamhive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamhive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_streamhive_proto_rawDescGZIP(), []int{3}
}

func (x *StopResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_UNKNOWN
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_streamhive_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamhive_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_streamhive_proto_rawDescGZIP(), []int{4}
}

func (x *StatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        JobStatus              `protobuf:"varint,1,opt,name=status,proto3,enum=streamhive.JobStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_streamhive_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamhive_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_streamhive_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_UNKNOWN
}

var File_streamhive_proto protoreflect.FileDescriptor

const file_streamhive_proto_rawDesc = "" +
	"\n" +
	"\x10streamhive.proto\x12\n" +
	"streamhive\"-\n" +
	"\fStartRequest\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x01 \x01(\tR\tstreamUrl\"&\n" +
	"\rStartResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"$\n" +
	"\vStopRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"=\n" +
	"\fStopResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.streamhive.JobStatusR\x06status\"&\n" +
	"\rStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"?\n" +
	"\x0eStatusResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.streamhive.JobStatusR\x06status*L\n" +
	"\tJobStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSTARTED\x10\x01\x12\f\n" +
	"\bFINISHED\x10\x02\x12\v\n" +
	"\aSTOPPED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042\xcc\x01\n" +
	"\rStreamService\x12<\n" +
	"\x05Start\x12\x18.streamhive.StartRequest\x1a\x19.streamhive.StartResponse\x129\n" +
	"\x04Stop\x12\x17.streamhive.StopRequest\x1a\x18.streamhive.StopResponse\x12B\n" +
	"\tGetStatus\x12\x19.streamhive.StatusRequest\x1a\x1a.streamhive.StatusResponseB\x06Z\x04.;pbb\x06proto3"

var (
	file_streamhive_proto_rawDescOnce sync.Once
	file_streamhive_proto_rawDescData []byte
)

func file_streamhive_proto_rawDescGZIP() []byte {
	file_streamhive_proto_rawDescOnce.Do(func() {
		file_streamhive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamhive_proto_rawDesc), len(file_streamhive_proto_rawDesc)))
	})
	return file_streamhive_proto_rawDescData
}

var file_streamhive_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamhive_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_streamhive_proto_goTypes = []any{
	(JobStatus)(0),         // 0: streamhive.JobStatus
	(*StartRequest)(nil),   // 1: streamhive.StartRequest
	(*StartResponse)(nil),  // 2: streamhive.StartResponse
	(*StopRequest)(nil),    // 3: streamhive.StopRequest
	(*StopResponse)(nil),   // 4: streamhive.StopResponse
	(*StatusRequest)(nil),  // 5: streamhive.StatusRequest
	(*StatusResponse)(nil), // 6: streamhive.StatusResponse
}
var file_streamhive_proto_depIdxs = []int32{
	0, // 0: streamhive.StopResponse.status:type_name -> streamhive.JobStatus
	0, // 1: streamhive.StatusResponse.status:type_name -> streamhive.JobStatus
	1, // 2: streamhive.StreamService.Start:input_type -> streamhive.StartRequest
	3, // 3: streamhive.StreamService.Stop:input_type -> streamhive.StopRequest
	5, // 4: streamhive.StreamService.GetStatus:input_type -> streamhive.StatusRequest
	2, // 5: streamhive.StreamService.Start:output_type -> streamhive.StartResponse
	4, // 6: streamhive.StreamService.Stop:output_type -> streamhive.StopResponse
	6, // 7: streamhive.StreamService.GetStatus:output_type -> streamhive.StatusResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_streamhive_proto_init() }
func file_streamhive_proto_init() {
	if File_streamhive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamhive_proto_rawDesc), len(file_streamhive_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streamhive_proto_goTypes,
		DependencyIndexes: file_streamhive_proto_depIdxs,
		EnumInfos:         file_streamhive_proto_enumTypes,
		MessageInfos:      file_streamhive_proto_msgTypes,
	}.Build()
	File_streamhive_proto = out.File
	file_streamhive_proto_goTypes = nil
	file_streamhive_proto_depIdxs = nil
}
